name = "ezan-plus-tetikleyici"
main = "index.js"
compatibility_date = "2026-08-15"

workers_dev = true
preview_urls = false

[vars]
GITHUB_REPO = "ezanplusapp/EzanPlusBot"

[triggers]
crons = ["45 16 * * *"]
